/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ComponentsSplatRouteImport } from './routes/components/$'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesSplatRouteImport } from './routes/templates/$'
import { Route as TransitionSlugRouteImport } from './routes/transition/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSplatRoute = ComponentsSplatRouteImport.update({
  id: '/components/$',
  path: '/components/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSplatRoute = TemplatesSplatRouteImport.update({
  id: '/templates/$',
  path: '/templates/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitionSlugRoute = TransitionSlugRouteImport.update({
  id: '/transition/$slug',
  path: '/transition/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/search': typeof ApiSearchRoute
  '/components/$': typeof ComponentsSplatRoute
  '/templates/$': typeof TemplatesSplatRoute
  '/transition/$slug': typeof TransitionSlugRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/search': typeof ApiSearchRoute
  '/components/$': typeof ComponentsSplatRoute
  '/templates/$': typeof TemplatesSplatRoute
  '/transition/$slug': typeof TransitionSlugRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/search': typeof ApiSearchRoute
  '/components/$': typeof ComponentsSplatRoute
  '/templates/$': typeof TemplatesSplatRoute
  '/transition/$slug': typeof TransitionSlugRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/search'
    | '/components/$'
    | '/templates/$'
    | '/transition/$slug'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/search'
    | '/components/$'
    | '/templates/$'
    | '/transition/$slug'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/search'
    | '/components/$'
    | '/templates/$'
    | '/transition/$slug'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ComponentsSplatRoute: typeof ComponentsSplatRoute
  TemplatesSplatRoute: typeof TemplatesSplatRoute
  TransitionSlugRoute: typeof TransitionSlugRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$': {
      id: '/components/$'
      path: '/components/$'
      fullPath: '/components/$'
      preLoaderRoute: typeof ComponentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$': {
      id: '/templates/$'
      path: '/templates/$'
      fullPath: '/templates/$'
      preLoaderRoute: typeof TemplatesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transition/$slug': {
      id: '/transition/$slug'
      path: '/transition/$slug'
      fullPath: '/transition/$slug'
      preLoaderRoute: typeof TransitionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiSearchRoute: ApiSearchRoute,
  ComponentsSplatRoute: ComponentsSplatRoute,
  TemplatesSplatRoute: TemplatesSplatRoute,
  TransitionSlugRoute: TransitionSlugRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
